version: '3.9'

services:

  rzd_db:
    image: postgres:15
    env_file:
      - postgres.env
    volumes:
      - ./rzd_db_data:/var/lib/postgresql/data/
    networks:
      - rzd_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      retries: 5
      timeout: 5s
    ports:
      - "7777:5432"

  pgadmin:
    image: dpage/pgadmin4:latest
    env_file:
      - pgadmin.env
    ports:
      - "5051:80"
    networks:
      - rzd_network

networks:
  rzd_network:
    driver: bridge
